### ISSUE TITLE
Ensure app works in portrait view on mobile

### ISSUE THREAD

**Issue by sjmatta** [DistributedInformationTechnologies/foodwatch#36]

**Comment by etrudeau** [comment]
Enable viewer to collapse details and filter boxes; float filter below FoodWatch title; push legend into help div and make help div into a modal.

**Comment by etrudeau** [comment]
1. Float filter below title
2. Make welcome div into a modal
3. Include legend in welcome modal
4. Make details collapsible
5. Make filter collapsible
